### PR TITLE
Updated website

### PR DESCRIPTION
**Pull request by eliaslfox**
I updated the website to not use php, and use elm. I'm open to suggestions if you think this needs work.

### CODE REVIEW

**Comment by possibly** [comment]
What do you think about my comments in issue #39?

**Comment by akmartinez1** [comment]
Tyler, side note,  promote an active member (like myself) on Slack to administer the channel there…

Sorry if this is not the appropriate place to bring it up but not sure how to contact you…

**Comment by possibly** [comment]
Hm, I dont believe I have admin on slack - someone else set it up.

**Comment by mileung** [comment]
Would be nice to use something like create-react-app and do something like this

https://blog.daftcode.pl/react-calendar-with-google-calendar-as-cms-tutorial-5f5d81e425a9

**Comment by possibly** [comment]
Sorry for the delay, @MiLeung 

I like the idea of using the Google Calendars API to store/pull data and then make a more responsive calendar display. You could probably hook the data right into any responsive calendar js library. I could imagine a nice tiny-mobile view that scales down to a 1-column series of vertically-stacked boxes/days. Maybe display 1 week by default (7 days) with a "next week" button that displays the next set of 7 boxes/days.

Btw, I gave @eliaslfox push rights and I think @MiLeung has push rights to this repo already?

I haven't tested this pull request, but it looks good 👍

**Pull request merged**
