### PR TITLE
redirects to https://ccsf-coders.github.io/

### PR DESCRIPTION
**Pull request by mileung**
The CCSF Coders website has been very troublesome. It seems like no one knows how to change it and many people are visiting it getting outdated information. This pull request redirects https://hills.ccsf.edu/~coders/ to our GitHub pages website. It'll be a lot easier for us to edit that way because not everyone knows how to use ssh or vim or Linux or stuff like that. Right now, our GitHub pages website is just plain html and css.

### CODE REVIEW

**Comment by possibly** [comment]
Nice idea!

I added @MiLeung to a team that should have full access to all repos -- feel free to merge this request when you see fit.

**Comment by possibly** [comment]
Heads up @MiLeung, I'm getting a 403 forbidden when accessing https://hills.ccsf.edu/~coders/

**Comment by mileung** [comment]
Same, I'm not sure why.

**Comment by possibly** [comment]
I believe the files need to be chmod'd to allow some group (other?) to access them.

Try `chmod -R 777 /the/www/dir`. Its kind of unsafe, but were not the server admins so not our problem 😃

**Pull request merged**
